name: PHPStan

on:
  push:
    branches: [main]
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - 'composer.json'
      - '.github/workflows/phpstan.yml'
  pull_request:
    paths:
      - '**.php'
      - 'phpstan.neon.dist'
      - 'composer.json'
      - '.github/workflows/phpstan.yml'

jobs:
  phpstan:
    runs-on: ubuntu-latest
    name: PHPStan

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.4'
          extensions: gd, exif, mbstring, dom, curl
          coverage: none

      - name: Install dependencies
        uses: ramsey/composer-install@v4
        with:
          dependency-versions: highest

      - name: Run PHPStan
        run: composer analyse -- --no-progress --error-format=github
